services:
  OHMedia\NewsBundle\Controller\ArticleController:
        tags: ["container.service_subscriber", "controller.service_arguments"]
        autowire: true

  OHMedia\NewsBundle\Repository\ArticleRepository:
    autowire: true
    tags: ['doctrine.repository_service']

  OHMedia\NewsBundle\Security\Voter\ArticleVoter:
    autowire: true
    tags: ['security.voter']

  OHMedia\NewsBundle\Service\ArticleNavItemProvider:
    autowire: true
    tags: ['oh_media_backend.nav_item_provider']

  OHMedia\NewsBundle\Service\ArticleEntityChoice:
    tags: ['oh_media_security.entity_choice']

  # Tags
  OHMedia\NewsBundle\Controller\ArticleTagController:
        tags: ["container.service_subscriber", "controller.service_arguments"]
        autowire: true

  OHMedia\NewsBundle\Repository\ArticleTagRepository:
    autowire: true
    tags: ['doctrine.repository_service']

  OHMedia\NewsBundle\Security\Voter\ArticleTagVoter:
    autowire: true
    tags: ['security.voter']

  OHMedia\NewsBundle\Service\ArticleTagNavItemProvider:
    autowire: true
    tags: ['oh_media_backend.nav_item_provider']

  OHMedia\NewsBundle\Service\ArticleTagEntityChoice:
    tags: ['oh_media_security.entity_choice']
