services:
    _defaults:
        autowire: true
        autoconfigure: true

    OHMedia\NewsBundle\:
        resource: '../src/'
        exclude:
            - '../src/Entity/'
            - '../src/OHMediaNewsBundle.php'

    OHMedia\NewsBundle\Security\Voter\ArticleTagVoter:
      arguments:
        $enabledArticleTags: '%oh_media_news.article_tags%'
