services:
    _defaults:
        autowire: true
        autoconfigure: true


    OHMedia\NewsBundle\:
        resource: '../src/'
        exclude:
            - '../src/Entity/'
            - '../src/OHMediaNewsBundle.php'
